---

- name: Pentest-cnc POC
  connection: ansible.netcommon.network_cli
  gather_facts: true
  hosts: nodes
  tasks:
    

    - name: Identify myself
      shell: hostname
      args:
        executable: /bin/bash
      register: myself

    - name: Identify myself 2
      debug:
        var: myself.stdout_lines

    - name: Update and upgrade apt packages
      become: true
      apt:
        name: 'nmap'
        update_cache: 'yes'

    - name: Set facts
      set_fact:
        target: "www.google.com"
        url_top_10k_subdomains: "https://raw.githubusercontent.com/rbsec/dnscan/master/subdomains-10000.txt"
    
    - stat: path=/tmp/wordlist-top-10k-subdomains
      register: wordlist_top_10k_subdomains


    - name: Download top-10k-subdomains wordlist if no exist
      shell: "curl {{ url_top_10k_subdomains|quote }} > {{ wordlist_top_10k_subdomains.stat.path }}"
      args:
        executable: /bin/bash
      when: wordlist_top_10k_subdomains.stat.exist


    - name: Run nmap top-10k scripts no-ping
      shell: nmap -sC --top-ports 10000 -Pn {{ target|quote }}
      args:
        executable: /bin/bash

    - name: Run dnsenum with to 10k subdomains
      shell: <HERE REPLACE WITH CMD>
      args:
        executable: /bin/bash

    - name: Run amass enumeration
      shell: amass enum -d {{ target|quote }} -ip
      args:
        executable: /bin/bash
