---

- name: Pentest-cnc POC
  gather_facts: true
  hosts: localhost  
  tasks:

    - name: Set facts
      set_fact:
        target: "www.google.com"
        url_top_10k_subdomains: "https://raw.githubusercontent.com/rbsec/dnscan/master/subdomains-10000.txt"

    - stat: path=/tmp/wordlist-top-10k-subdomains
      register: wordlist_top_10k_subdomains

    - name: Install nmap
      become: true
      apt:
        name: 'nmap'
        update_cache: 'yes'

    - name: Install dnsenum
      become: true
      apt:
        name: 'dnsenum'
        update_cache: 'yes'

    - name: Download top-10k-subdomains wordlist if no exist
      shell: "curl {{ url_top_10k_subdomains|quote }} > {{ wordlist_top_10k_subdomains.stat.path }}"
      when: wordlist_top_10k_subdomains.stat.exists

    - name: Run nmap top-10k scripts no-ping
      shell: nmap -sC --top-ports 10000 -Pn {{ target|quote }} > /tmp/{{ target|quote|replace('.','-') }}-nmap

    - name: Run dnsenum with to 10k subdomains
      shell: dnsenum -v -f {{ wordlist_top_10k_subdomains.stat.path }} {{ target|quote }} -o /tmp/{{ target|quote|replace('.','-') }}-dnsenum

    - name: Run amass enumeration
      shell: amass enum -d {{ target|quote }} -ip > /tmp/{{ target|quote|replace('.','-') }}-amass